import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/app/components/theme-provider';
import Navbar from '@/app/components/Navbar';
import prisma from '@/app/lib/db';
import { getKindeServerSession } from '@kinde-oss/kinde-auth-nextjs/server';
import { unstable_noStore } from 'next/cache';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function getData(userId: string) {
  unstable_noStore();
  if (!userId) return console.error('No user id');

  const data = await prisma.user.findUnique({
    where: {
      id: userId,
    },
    select: {
      colorScheme: true,
    },
  });

  return data;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getKindeServerSession().getUser();
  const data = await getData(user?.id as string);
  return (
    <html lang='en'>
      <body
        className={`${inter.className} ${data?.colorScheme ?? 'theme-orange'}`}
      >
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
